  swagger: "2.0"
  info: 
    title: "Alert Policy Engine API"
    description: "API documentation for platform and policy engine"
  consumes:
    - application/json
  produces: 
    - application/json